<?php
$boletos = array(
  array('id' => 15, 'label' => "VENDA A PRAZO 28 DIAS BOLETO"),
  array('id' => 25, 'label' => "VENDA A PRAZO 21 DIAS / BOLETO"),
  array('id' => 208, 'label' => "VENDAS BOLETO 7"),
  array('id' => 209, 'label' => "VENDAS BOLETO 15"),
  array('id' => 600, 'label' => "BOLETO 1+1"),
  array('id' => 610, 'label' => "BOLETO 1+2"),
  array('id' => 620, 'label' => "BOLETO 1+3"),
  array('id' => 630, 'label' => "BOLETO 1+4"),
  array('id' => 640, 'label' => "BOLETO 1+5"),
  array('id' => 650, 'label' => "BOLETO 1+6"),
  array('id' => 651, 'label' => "BOLETO 1+9"),
  array('id' => 653, 'label' => "BOLETO 1+11"),
  array('id' => 656, 'label' => "BOLETO 1+14"),
  array('id' => 657, 'label' => "BOLETO 1+18"),
  array('id' => 658, 'label' => "BOLETO 1+12"),
  array('id' => 659, 'label' => "BOLETO 1+7"),
  array('id' => 663, 'label' => "BOLETO 1+15"),
  array('id' => 664, 'label' => "BOLETO 1+20"),
  array('id' => 665, 'label' => "BOLETO 1+8"),
  array('id' => 666, 'label' => "BOLETO 1+13"),
  array('id' => 667, 'label' => "BOLETO 1+16"),
  array('id' => 670, 'label' => "BOLETO 1+19"),
  array('id' => 672, 'label' => "BOLETO 20 / 40 DIAS"),
  array('id' => 679, 'label' => "BOLETO 1+10"),
  array('id' => 694, 'label' => "BOLETO 1+24"),
  array('id' => 695, 'label' => "BOLETO 1+23"),
  array('id' => 696, 'label' => "BOLETO 1+26"),
  array('id' => 697, 'label' => "BOLETO 1+21"),
  array('id' => 699, 'label' => "BOLETO 1+17"),
  array('id' => 754, 'label' => "BOLETO 1+10")
);
$current = $this->htmlEscape($this->getInfoData('boleto_sankhya_id'));
?>

<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
  <input id="boleto_descricao" type="hidden" name="payment[boleto_descricao]">
  <!-- <div>
    <label><?php echo $this->__('Custom Field One') ?>*</label>
    <span>
      <input type="text" title="<?php echo $this->__('Custom Field One') ?>" name="payment[boleto_sankhya_id]" value="<?php echo $this->htmlEscape($this->getInfoData('boleto_sankhya_id')) ?>" />
    </span>
  </div> -->
  <div>
    <label><?php echo $this->__('Selecione as parcelas') ?>*</label>
    <span>
      <!-- <input type="text" title="<?php echo $this->__('Custom Field Two') ?>" name="payment[boleto_descricao]" value="<?php echo $this->htmlEscape($this->getInfoData('boleto_descricao')) ?>" /> -->
      <select name="payment[boleto_sankhya_id]" onchange="$('boleto_descricao').value = event.target.selectedOptions[0].label;">
         <option value="" disabled selected>Selecione uma opição</option>
        <?php foreach ($boletos as $boleto) { ?>
        <option value="<?php echo $boleto['id']?>" <?php if ($boleto['id'] == $current) echo 'selected';?>><?php echo $boleto['label']?></option>
        <?php } ?>
      </select>
    </span>
  </div>
</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
